export const SERVER_MAX_TASKS_PER_REQUEST = 100;
export const SERVER_MAX_ALLOWED_TASKS_COUNT = 100;
export const SERVER_DEFAULT_TASKS_PER_REQUEST = 10;
export const SERVER_ENTITY_MAX_TITLE_LENGTH = 100;
export const SERVER_TASK_MAX_DESCRIPTION_LENGTH = 1000;
export const SERVER_MAX_ALLOWED_LISTS_COUNT = 10;
